image_filter:
  initialisation:
    file_path: '/home/florianthaler/Documents/research/bilevel_optimisation/bilevel_optimisation/model_data/foe_filters_7x7_chen-ranftl-pock_2014_scaled.pt'
  trainable: False

potential:
  spline:
    initialisation:
      mode: 'student_t'
      multiplier: 0.0005
    trainable: True

measurement_model:
  noise_level: 0.1
  forward_operator: 'Identity'

data:
  type: 'float32'
  dataset:
    train:
      root_dir: '/home/florianthaler/Documents/data/image_data/BSDS300/images/train'
      crop_size: 64
      batch_size: 128
    test:
      root_dir: '/home/florianthaler/Documents/data/image_data/some_images'

energy:
  lam: 10