data:
  type: 'float32'
  dataset:
    test:
      root_dir: '/home/florianthaler/Documents/data/image_data/some_images'

image_filter:
  initialisation:
    mode: 'randn'
  multiplier: 5
  trainable: True

potential:
  spline:
    initialisation:
      mode: uniform
      nodes:
    multiplier: 1

energy:
  lam: 0.5


