data:
  type: 'float32'         # values in ['float16', 'float32', 'float64']
  dataset:
    train:
      root_dir: 'TODO: fill me'
      batch_size: 32
      crop_size: 64
    test:
      root_dir: 'TODO: fill me'

image_filter:
  filter_dim: 7
  padding: 3
  padding_mode: 'reflect'
  orthogonality:
    enable: False
    max_num_iterations: 3
  initialisation:
    mode: 'dct'
    multiplier: 1.0
    normalise: False
  apply_unit_ball_projection: False
  trainable: False

potential:
  student_t:
    num_marginals: 48
    initialisation:
      mode: 'uniform'
      multiplier: 1.0
    trainable: False
  quartic_bspline:
    num_marginals: 48
    num_centers: 9
    box_lower: -3
    box_upper: 3
    initialisation:
      mode: 'student_t'
      multiplier: 1.0
    trainable: False

measurement_model:
  noise_level: 0.1
  forward_operator: 'Identity'

energy:
  lam: 0.1

