regulariser:
  potential:
    name: 'LinearSpline'
    parameters:
      linear_spline:
        num_nodes: 37
        box_lower: -1.0
        box_upper: 1.0
        initialisation:
          name: 'student_t'
          multiplier: 0.001                 # applied iff model is not loaded from file
        trainable: True
  image_filter:
    trainable: False
    initialisation:
      file: 'foe_filters_7x7_chen-ranftl-pock_2014.pt'
      multiplier: 255

inner_energy:
  type: 'OptimisationEnergy'
  lam: 0.5
  optimiser:
    name: 'NAGOptimiser'
    use_prox: False
    parameters: {lip_const: 1000}
    stopping:
      name: 'FixedIterationsStopping'
      parameters: {max_num_iterations: 1000}

bilevel:
  optimiser:
    name: 'Adam'
    parameters: {lr: 0.0001}

data:
  type: 'float32'
  dataset:
    train:
      root_dir: '/home/florianthaler/Documents/data/image_data/BSDS300/images/train'
    test:
      root_dir: '/home/florianthaler/Documents/data/image_data/some_images'


