data:
  type: 'float32'
  dataset:
    train:
      root_dir: '/home/florianthaler/Documents/data/image_data/BSDS300/images/train'
    test:
      root_dir: '/home/florianthaler/Documents/data/image_data/some_images'

image_filter:
  initialisation:
    file_path: '/home/florianthaler/Documents/research/bilevel_optimisation/bilevel_optimisation/model_data/foe_filters_7x7_chen-ranftl-pock_2014_scaled.pt'

potential:
  student_t:
    initialisation:
      mode: 'uniform'
      multiplier: 0.0005
    trainable: True

energy:
  lam: 10