data:
  type: 'float32'
  dataset:
    test:
      root_dir: '/home/florianthaler/Documents/data/image_data/BSDS68_rotated'

image_filter:
  initialisation:
    file_path: '/home/florianthaler/Documents/trash/00043/models/filters_iter_14999.pt'
  trainable: False

potential:
  student_t:
    initialisation:
      file_path: '/home/florianthaler/Documents/trash/00043/models/potential_iter_14999.pt'
    trainable: False

energy:
  lam: 100