regulariser:
  potential:
    name: 'StudentT'
    parameters:
      student_t:
        initialisation:
          name: 'uniform'
          multiplier: 0.01
        trainable: True
  image_filter:
    padding_mode: 'reflect'
    initialisation:
      file: ''
      multiplier: 50.0
      parameters:
        name: 'dct'
        filter_dim: 7
    trainable: True

inner_energy:
  type: 'OptimisationEnergy'
  lam: 0.1
  optimiser:
    name: 'NAGOptimiser'
    stopping:
      name: 'FixedIterationsStopping'

bilevel:
  loss: 'L2Loss'
  optimiser:
    name: 'Adam'
    parameters: {lr: 0.0005}

data:
  type: 'float32'
  dataset:
    train:
      root_dir: '/home/florianthaler/Documents/data/image_data/BSDS300/images/train'
    test:
      root_dir: '/home/florianthaler/Documents/data/image_data/some_images'