regulariser:
  potential:
    name: 'StudentT'
  filters:
    padding_mode: 'reflect'
    initialisation:
      file: 'foe_filters_7x7_chen-ranftl-pock_2014.pt'
      multiplier: 255.0
    trainable: False
  filter_weights:
    initialisation:
      multiplier: 0.001
      parameters:
        name: 'uniform'         # values in ['uniform']
    trainable: True

inner_energy:
  lam: 0.5
  optimiser:
    name: 'NAGOptimiser'
    use_prox: False
    stopping:
      name: 'EarlyStopping'
      parameters: {max_num_iterations: 1000, rel_tol: 0.00001}

bilevel:
  optimiser:
    name: 'NAGOptimiser'
    parameters: {beta: 0.71, lip_const_default: 100000}

data:
  type: 'float32'
  dataset:
    train:
      root_dir: '/home/florianthaler/Documents/data/image_data/BSDS300/images/train'
    test:
      root_dir: '/home/florianthaler/Documents/data/image_data/some_images'