data:
  type: 'float32'         # values in ['float16', 'float32', 'float64']
  dataset:
    train:
      root_dir: 'TODO: fill me'
      batch_size: 32
      crop_size: 64
    test:
      root_dir: 'TODO: fill me'
  models:
    root_dir: ''                  # if not specified, 'bilevel_optimisation/model_data' is used to load models from
  experiments:
    root_dir: ''

image_filter:
  filter_dim: 7
  padding_mode: 'reflect'
  initialisation:
    mode: 'dct'
    file_path: ''
  multiplier: 1.0
  trainable: False


potential:
  student_t:
    initialisation:
      mode: 'uniform'
      file_path: ''
    multiplier: 1.0
    trainable: False

measurement_model:
  noise_level: 0.1
  forward_operator: 'Identity'

energy:
  lam: 0.1

