data:
  type: 'float32'
  dataset:
    test:
      root_dir: '/home/florianthaler/Documents/data/image_data/BSDS300/images/test_as_landscape' # '/home/florianthaler/Documents/data/BSDS300/images/test_as_landscape' # /image_data/some_images' #

image_filter:
  initialisation:
    file_path: '/home/florianthaler/Documents/research/bilevel_optimisation/bilevel_optimisation/model_data/foe_filters_7x7_chen-ranftl-pock_2014_scaled.pt'

potential:
  spline:
    num_nodes: 19
    box_lower: -3
    box_upper: 3
    initialisation:
      mode: 'student_t'
      file_path: ''
    trainable: False

energy:
  lam: 0.5