regulariser:
  potential:
    name: 'StudentT'
    parameters:
      student_t:
        initialisation:
          name: 'uniform'
          multiplier: 0.001
        trainable: True
  image_filter:
    trainable: False
    initialisation:
      file: 'foe_filters_7x7_chen-ranftl-pock_2014.pt'
      multiplier: 255

inner_energy:
  type: 'UnrollingEnergy'
  lam: 0.5
  optimiser:
    name: 'UnrollingNAGOptimiser'
    use_prox: False
    parameters: {alpha: 0.0001}
    stopping:
      name: 'FixedIterationsStopping'
      parameters: {max_num_iterations: 10}

bilevel:
  optimiser:
    name: 'NAGOptimiser'
    parameters: {beta: 0.71, lip_const_default: 100000}

data:
  type: 'float64'
  dataset:
    train:
      root_dir: '/home/florianthaler/Documents/data/image_data/BSDS300/images/train'
    test:
      root_dir: '/home/florianthaler/Documents/data/image_data/some_images'


